name: backend
description: backend using Yannick framework.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  postgres: ^2.4.3
  path: ^1.8.0
  backend_framework:
    path: ../backend_framework

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
