name: backend
description: backend using Yannick framework.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  postgres: ^2.4.3
  dart_jsonwebtoken: ^2.4.1
  encrypt: ^5.0.1
  path: ^1.8.0
  cobalt:
    git: 
      url: https://github.com/Shiranuit/Cobalt.git
      ref: master

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
